import { BaseModel } from '../../../../../../core/_base/crud/models/_base.model';

export class HoSoNCCModel extends BaseModel {
	Id: number;
	NgayGui: any;
	SoHoSo: string;
	Id_DoiTuongNCC: number;
	Id_LoaiHoSo: number;
	HoTen: string;
	BiDanh: string;
	NgaySinh: string;
	GioiTinh: number;
	NamSinh: number;
	Id_Xa: number;
	Id_KhomAp: number;
	Id_DanToc: number;
	Id_TonGiao: number;
	DiaChi: string;
	SDT: string;
	Email: string;
	NguyenQuan: string;
	TruQuan: string;
	IsChet: boolean;
	NgayChet: number;
	SoKhaiTu: number;
	NgayKhaiTu: number;
	NoiKhaiTu: number;
	IsThanNhan: boolean;
	Id_ThanNhan: number;
	NguoiThoCungLietSy: string;
	NguyenQuan1: string;
	TruQuan1: string;
	NgaySinh1: string;
	NamSinh1: number;
	GioiTinh1: number;
	IsChet1: number;
	NgayChet1: number;
	SoKhaiTu1: number;
	NgayKhaiTu1: number;
	NoiKhaiTu1: number;
	QuanHeVoiLietSy: number;
	ProvinceID: number;
	DistrictID: number;
	NgayNhapNgu: string;
	NgayXuatNgu: string;
	NoiCongTac: string;
	CapBac: string;
	ChucVu: string;
	Ngay_: string;
	TruongHop_: string;
	Noi_: string;
	Mo: number;//1: Nghĩa trang, 2: Gia đình quản lý, 3: Không có thông tin
	TiLe: number;

	LyDoGTYKhoa: string;
	LyDoDinhChi: string;
	ThuHoiDCTu: number;
	ThuHoiDCDen: number;
	LyDoTamDC: string;
	TGThamGiaKC: number;
	BangKhenCacCap: string;
	NgayHS: string;
	NoiHS: string;
	NgayHop: string;
    GioHop: string
    ThanhPhanHop: string;
    NoiDungHop: string;
	CanCuLietSy: string;
	LyDoTangTuat: string;
	LyDoDinhChinhTN: string;
	LyDoThoCung: string;
	XetToTrinh: string;
	ND_HuanChuong: string;
	TinhTrangHT: number;
	GhiChuTruyTang: string;
	ND_CanCu: string;

	FileDinhKem: any;
	GiayTos: any[];

	DiChuyenModel: any;
	ThanNhanModel: any;
	ThanNhanDaMat: any;
	HoatDongModel: any;
	DinhChinhModel: any;
	AllowEdit: boolean;
	IsGiam: boolean;
	clear() {
		this.Id = 0;
		this.NgayGui = null;
		this.SoHoSo = '';
		this.Id_DoiTuongNCC = null;
		this.Id_LoaiHoSo = null;
		this.NamSinh = null;
		this.Id_Xa = null;
		this.Id_KhomAp = null;
		this.IsChet = false;
		this.Id_ThanNhan = null;
		this.IsThanNhan = false;
		this.NguoiThoCungLietSy = '';
		this.NguyenQuan1 = '';
		this.TruQuan1 = '';
		this.NgaySinh1 = '';
		this.NamSinh1 = null;
		this.GioiTinh1 = 1;
		this.QuanHeVoiLietSy = null;
		this.DistrictID = null;
		this.HoTen = '';
		this.NgaySinh = '';
		this.GioiTinh = 1;
		this.DiaChi = '';
		this.SDT = '';
		this.Email = '';
		this.ProvinceID = null;
		this.DistrictID = null;
		this.Mo = 0;
		this.TiLe = null;
		this.LyDoGTYKhoa = null;
		this.LyDoDinhChi = null;
		this.ThuHoiDCTu = 0;
		this.ThuHoiDCDen = 0;
		this.LyDoTamDC = null;
		this.BangKhenCacCap = null;
		this.TGThamGiaKC = 0;
		this.NgayHS = '';
		this.NoiHS = '';
		this.NgayHop = '';
		this.GioHop = '';
		this.ThanhPhanHop = '';
		this.NoiDungHop = '';
		this.CanCuLietSy = null;
		this.LyDoTangTuat = null;
		this.LyDoDinhChinhTN = null;
		this.ND_CanCu = null;
		this.LyDoThoCung = null;
		this.XetToTrinh = null;
		this.ND_HuanChuong = null;
		this.GiayTos = [];
		this.AllowEdit = true;
		this.ThanNhanModel = null;
		this.HoatDongModel = null;
		this.DinhChinhModel = null;
		this.DiChuyenModel = null;
		this.IsGiam = false;
	}
}
