import { BaseModel } from '../../../../../../core/_base/crud/models/_base.model';

export class HoSoNCCModel extends BaseModel {
	Id: number = 0;
	NgayGui: any;
	SoHoSo: string = "";
	Id_DoiTuongNCC: number | null = null;
	Id_LoaiHoSo: number | null = null;
	HoTen: string = "";
	BiDanh: string = "";
	NgaySinh: string = "";
	GioiTinh: number = 0;
	NamSinh: number | null = null;
	Id_Xa: number | null = null;
	Id_KhomAp: number | null = null;
	Id_DanToc: number | null = null;;
	Id_TonGiao: number | null = null;
	DiaChi: string = ""; 
	SDT: string = "";
	Email: string = "";
	NguyenQuan: string = "";
	TruQuan: string = "";
	IsChet: boolean = false;
	NgayChet: number = 0;
	SoKhaiTu: number = 0;
	NgayKhaiTu: number = 0;
	NoiKhaiTu: number = 0;
	IsThanNhan: boolean = false;
	Id_ThanNhan: number | null = null;
	NguoiThoCungLietSy: string = "";
	NguyenQuan1: string = "";
	TruQuan1: string = "";
	NgaySinh1: string = "";
	NamSinh1: number | null = null;
	GioiTinh1: number = 0;
	IsChet1: number = 0;
	NgayChet1: number = 0;
	SoKhaiTu1: number = 0;
	NgayKhaiTu1: number = 0;
	NoiKhaiTu1: number = 0;
	QuanHeVoiLietSy: number | null = null;
	ProvinceID: number | null = null;
	DistrictID: number | null = null;
	NgayNhapNgu: string = "";
	NgayXuatNgu: string = "";
	NoiCongTac: string = "";
	CapBac: string = "";
	ChucVu: string = "";
	Ngay_: string = "";
	TruongHop_: string = "";
	Noi_: string = "";
	Mo: number = 0;//1: Nghĩa trang, 2: Gia đình quản lý, 3: Không có thông tin
	TiLe: number | null = null;
	LyDoGTYKhoa: string | null = null;
	LyDoDinhChi: string | null = null;
	ThuHoiDCTu: number = 0;
	ThuHoiDCDen: number = 0;
	LyDoTamDC: string | null = null;
	TGThamGiaKC: number = 0;
	BangKhenCacCap: string | null = null;
	NgayHS: string = "";
	NoiHS: string = "";
	NgayHop: string = "";
    GioHop: string = "";
    ThanhPhanHop: string = "";
    NoiDungHop: string = "";
	CanCuLietSy: string | null = null;
	LyDoTangTuat: string | null = null;
	LyDoDinhChinhTN: string | null = null;
	LyDoThoCung: string | null = null;
	XetToTrinh: string | null = null;
	ND_HuanChuong: string | null = null;
	TinhTrangHT: number = 0;
	GhiChuTruyTang: string = "";
	ND_CanCu: string | null = null;

	FileDinhKem: any;
	GiayTos: any[] = [];

	DiChuyenModel: any;
	ThanNhanModel: any;
	ThanNhanDaMat: any;
	HoatDongModel: any;
	DinhChinhModel: any;
	AllowEdit: boolean = true;
	IsGiam: boolean = false;

	clear() {
		this.Id = 0;
		this.NgayGui = null;
		this.SoHoSo = '';
		this.Id_DoiTuongNCC = null;
		this.Id_LoaiHoSo = null;
		this.NamSinh = null;
		this.Id_Xa = null;
		this.Id_KhomAp = null;
		this.IsChet = false;
		this.Id_ThanNhan = null;
		this.IsThanNhan = false;
		this.NguoiThoCungLietSy = '';
		this.NguyenQuan1 = '';
		this.TruQuan1 = '';
		this.NgaySinh1 = '';
		this.NamSinh1 = null;
		this.GioiTinh1 = 1;
		this.QuanHeVoiLietSy = null;
		this.DistrictID = null;
		this.HoTen = '';
		this.NgaySinh = '';
		this.GioiTinh = 1;
		this.DiaChi = '';
		this.SDT = '';
		this.Email = '';
		this.ProvinceID = null;
		this.DistrictID = null;
		this.Mo = 0;
		this.TiLe = null;
		this.LyDoGTYKhoa = null;
		this.LyDoDinhChi = null;
		this.ThuHoiDCTu = 0;
		this.ThuHoiDCDen = 0;
		this.LyDoTamDC = null;
		this.BangKhenCacCap = null;
		this.TGThamGiaKC = 0;
		this.NgayHS = '';
		this.NoiHS = '';
		this.NgayHop = '';
		this.GioHop = '';
		this.ThanhPhanHop = '';
		this.NoiDungHop = '';
		this.CanCuLietSy = null;
		this.LyDoTangTuat = null;
		this.LyDoDinhChinhTN = null;
		this.ND_CanCu = null;
		this.LyDoThoCung = null;
		this.XetToTrinh = null;
		this.ND_HuanChuong = null;
		this.GiayTos = [];
		this.AllowEdit = true;
		this.ThanNhanModel = null;
		this.HoatDongModel = null;
		this.DinhChinhModel = null;
		this.DiChuyenModel = null;
		this.IsGiam = false;
	}
}
